objects/copado__Function__c.object
<CustomObject>
    <description>A function is a script that contains a series of commands and can be executed from Copado.</description>
    <label>Function</label>
    <nameField>
        <label>Function Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Functions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/copado__Result__c.object
<CustomObject>
    <description>A unified place to look for job results when working with automations such as functions or Salesforce flows.</description>
    <fields>
        <fullName>copado__Function__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the function that triggered the result.</description>
        <inlineHelpText>Lookup field to the function that triggered the result.</inlineHelpText>
        <label>Function</label>
        <referenceTo>copado__Function__c</referenceTo>
        <relationshipLabel>Results</relationshipLabel>
        <relationshipName>Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Result</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JestScanCallback.cls
Global class JestScanCallback implements copado.MCCallback {
    Global void execute(copado__Function__c function, copado__Result__c result, String status) {
        if(status == 'Failed') {
            System.debug('Failed');
            System.debug('function' + function);
            System.debug('status' + status);
            System.debug('result' + result);
        } else if(status == 'Success') {
            System.debug('Passed');
            System.debug('function' + function);
            System.debug('status' + status);
            System.debug('result' + result);
        } else {
            System.debug('still running');
        }
    }
}